### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [ntsystemsit/ntsystemsit.github.io#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`2015-08-23-getting-started-with-osx.md`](https://github.com/ntsystemsit/ntsystemsit.github.io/blob/677e3aa59b1ee4a7ca8550eb3fcfc9547e0a3159/_posts/Archive/2015-08-23-getting-started-with-osx.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by tomtorggler** [comment]
Fixed it, thanks for reaching out.
